# Generated by Django 4.2.4 on 2023-08-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='liste_taches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=500)),
                ('date_creation', models.DateTimeField(verbose_name='Date et heure de création de la tâche')),
                ('date_cloture', models.DateTimeField(default=None, verbose_name='Date et heure de cloture de la tâche')),
            ],
        ),
    ]
